export const dummyData = [
  {
    AccountName: "",
    Cr: 0,
    Discount: null,
    DiscountAmount: null,
    FeeAmount: 0,
    IDAccountType: 0,
    Narration: null,
    PercentageDiscount: null,
    checked: false,
  },
  {
    AccountName: "",
    Cr: 0,
    Discount: null,
    DiscountAmount: null,
    FeeAmount: 0,
    IDAccountType: 0,
    Narration: null,
    PercentageDiscount: null,
    checked: false,
  },
  {
    AccountName: "",
    Cr: 0,
    Discount: null,
    DiscountAmount: null,
    FeeAmount: 0,
    IDAccountType: 0,
    Narration: null,
    PercentageDiscount: null,
    checked: false,
  },
  {
    AccountName: "",
    Cr: 0,
    Discount: null,
    DiscountAmount: null,
    FeeAmount: 0,
    IDAccountType: 0,
    Narration: null,
    PercentageDiscount: null,
    checked: false,
  },
  {
    AccountName: "",
    Cr: 0,
    Discount: null,
    DiscountAmount: null,
    FeeAmount: 0,
    IDAccountType: 0,
    Narration: null,
    PercentageDiscount: null,
    checked: false,
  },
  {
    AccountName: "",
    Cr: 0,
    Discount: null,
    DiscountAmount: null,
    FeeAmount: 0,
    IDAccountType: 0,
    Narration: null,
    PercentageDiscount: null,
    checked: false,
  },
  {
    AccountName: "",
    Cr: 0,
    Discount: null,
    DiscountAmount: null,
    FeeAmount: 0,
    IDAccountType: 0,
    Narration: null,
    PercentageDiscount: null,
    checked: false,
  },
  {
    AccountName: "",
    Cr: 0,
    Discount: null,
    DiscountAmount: null,
    FeeAmount: 0,
    IDAccountType: 0,
    Narration: null,
    PercentageDiscount: null,
    checked: false,
  },
  {
    AccountName: "",
    Cr: 0,
    Discount: null,
    DiscountAmount: null,
    FeeAmount: 0,
    IDAccountType: 0,
    Narration: null,
    PercentageDiscount: null,
    checked: false,
  },
  {
    AccountName: "",
    Cr: 0,
    Discount: null,
    DiscountAmount: null,
    FeeAmount: 0,
    IDAccountType: 0,
    Narration: null,
    PercentageDiscount: null,
    checked: false,
  },
];
