export const GET_ALL_LEDGER_ACCOUNT_WISE_REQUEST =
  "GET_ALL_LEDGER_ACCOUNT_WISE_REQUEST";
export const GET_ALL_LEDGER_ACCOUNT_WISE_SUCCESS =
  "GET_ALL_LEDGER_ACCOUNT_WISE_SUCCESS";
export const GET_ALL_LEDGER_ACCOUNT_WISE_FAIL =
  "GET_ALL_LEDGER_ACCOUNT_WISE_FAIL";
export const GET_ALL_LEDGER_ACCOUNT_WISE_RESET =
  "GET_ALL_LEDGER_ACCOUNT_WISE_RESET";

export const GET_LIST_LEDGER_ACCOUNT_WISE_REQUEST =
  "GET_LIST_LEDGER_ACCOUNT_WISE_REQUEST";
export const GET_LIST_LEDGER_ACCOUNT_WISE_SUCCESS =
  "GET_LIST_LEDGER_ACCOUNT_WISE_SUCCESS";
export const GET_LIST_LEDGER_ACCOUNT_WISE_FAIL =
  "GET_LIST_LEDGER_ACCOUNT_WISE_FAIL";
export const GET_LIST_LEDGER_ACCOUNT_WISE_RESET =
  "GET_LIST_LEDGER_ACCOUNT_WISE_RESET";

export const GET_ACTIVE_LEDGER_ACCOUNT_WISE_REQUEST =
  "GET_ACTIVE_LEDGER_ACCOUNT_WISE_REQUEST";
export const GET_ACTIVE_LEDGER_ACCOUNT_WISE_SUCCESS =
  "GET_ACTIVE_LEDGER_ACCOUNT_WISE_SUCCESS";
export const GET_ACTIVE_LEDGER_ACCOUNT_WISE_FAIL =
  "GET_ACTIVE_LEDGER_ACCOUNT_WISE_FAIL";
export const GET_ACTIVE_LEDGER_ACCOUNT_WISE_RESET =
  "GET_ACTIVE_LEDGER_ACCOUNT_WISE_RESET";
