export const GET_ALL_ADMISSION_FEE_STRUCTURE_REQUEST =
  "GET_ALL_ADMISSION_FEE_STRUCTURE_REQUEST";
export const GET_ALL_ADMISSION_FEE_STRUCTURE_SUCCESS =
  "GET_ALL_ADMISSION_FEE_STRUCTURE_SUCCESS";
export const GET_ALL_ADMISSION_FEE_STRUCTURE_FAIL =
  "GET_ALL_ADMISSION_FEE_STRUCTURE_FAIL";
export const GET_ALL_ADMISSION_FEE_STRUCTURE_RESET =
  "GET_ALL_ADMISSION_FEE_STRUCTURE_RESET";

export const GET_LIST_ADMISSION_FEE_STRUCTURE_REQUEST =
  "GET_LIST_ADMISSION_FEE_STRUCTURE_REQUEST";
export const GET_LIST_ADMISSION_FEE_STRUCTURE_SUCCESS =
  "GET_LIST_ADMISSION_FEE_STRUCTURE_SUCCESS";
export const GET_LIST_ADMISSION_FEE_STRUCTURE_FAIL =
  "GET_LIST_ADMISSION_FEE_STRUCTURE_FAIL";
export const GET_LIST_ADMISSION_FEE_STRUCTURE_RESET =
  "GET_LIST_ADMISSION_FEE_STRUCTURE_RESET";

export const GET_SINGLE_TO_CREATE_ADMISSION_FEE_STRUCTURE_REQUEST =
  "GET_SINGLE_TO_CREATE_ADMISSION_FEE_STRUCTURE_REQUEST";
export const GET_SINGLE_TO_CREATE_ADMISSION_FEE_STRUCTURE_SUCCESS =
  "GET_SINGLE_TO_CREATE_ADMISSION_FEE_STRUCTURE_SUCCESS";
export const GET_SINGLE_TO_CREATE_ADMISSION_FEE_STRUCTURE_FAIL =
  "GET_SINGLE_TO_CREATE_ADMISSION_FEE_STRUCTURE_FAIL";
export const GET_SINGLE_TO_CREATE_ADMISSION_FEE_STRUCTURE_RESET =
  "GET_SINGLE_TO_CREATE_ADMISSION_FEE_STRUCTURE_RESET";

export const GET_SINGLE_TO_EDIT_ADMISSION_FEE_STRUCTURE_REQUEST =
  "GET_SINGLE_TO_EDIT_ADMISSION_FEE_STRUCTURE_REQUEST";
export const GET_SINGLE_TO_EDIT_ADMISSION_FEE_STRUCTURE_SUCCESS =
  "GET_SINGLE_TO_EDIT_ADMISSION_FEE_STRUCTURE_SUCCESS";
export const GET_SINGLE_TO_EDIT_ADMISSION_FEE_STRUCTURE_FAIL =
  "GET_SINGLE_TO_EDIT_ADMISSION_FEE_STRUCTURE_FAIL";
export const GET_SINGLE_TO_EDIT_ADMISSION_FEE_STRUCTURE_RESET =
  "GET_SINGLE_TO_EDIT_ADMISSION_FEE_STRUCTURE_RESET";

export const POST_ADMISSION_FEE_STRUCTURE_REQUEST =
  "POST_ADMISSION_FEE_STRUCTURE_REQUEST";
export const POST_ADMISSION_FEE_STRUCTURE_SUCCESS =
  "POST_ADMISSION_FEE_STRUCTURE_SUCCESS";
export const POST_ADMISSION_FEE_STRUCTURE_FAIL =
  "POST_ADMISSION_FEE_STRUCTURE_FAIL";
export const POST_ADMISSION_FEE_STRUCTURE_RESET =
  "POST_ADMISSION_FEE_STRUCTURE_RESET";

export const PUT_ADMISSION_FEE_STRUCTURE_REQUEST =
  "PUT_ADMISSION_FEE_STRUCTURE_REQUEST";
export const PUT_ADMISSION_FEE_STRUCTURE_SUCCESS =
  "PUT_ADMISSION_FEE_STRUCTURE_SUCCESS";
export const PUT_ADMISSION_FEE_STRUCTURE_FAIL =
  "PUT_ADMISSION_FEE_STRUCTURE_FAIL";
export const PUT_ADMISSION_FEE_STRUCTURE_RESET =
  "PUT_ADMISSION_FEE_STRUCTURE_RESET";
