export const GET_ALL_ACCOUNT_HEADER_REQUEST = "GET_ALL_ACCOUNT_HEADER_REQUEST";
export const GET_ALL_ACCOUNT_HEADER_SUCCESS = "GET_ALL_ACCOUNT_HEADER_SUCCESS";
export const GET_ALL_ACCOUNT_HEADER_FAIL = "GET_ALL_ACCOUNT_HEADER_FAIL";
export const GET_ALL_ACCOUNT_HEADER_RESET = "GET_ALL_ACCOUNT_HEADER_RESET";

export const GET_LIST_ACCOUNT_HEADER_REQUEST = "GET_LIST_ACCOUNT_HEADER_REQUEST";
export const GET_LIST_ACCOUNT_HEADER_SUCCESS = "GET_LIST_ACCOUNT_HEADER_SUCCESS";
export const GET_LIST_ACCOUNT_HEADER_FAIL = "GET_LIST_ACCOUNT_HEADER_FAIL";
export const GET_LIST_ACCOUNT_HEADER_RESET = "GET_LIST_ACCOUNT_HEADER_RESET";

export const GET_SINGLE_TO_CREATE_ACCOUNT_HEADER_REQUEST = "GET_SINGLE_TO_CREATE_ACCOUNT_HEADER_REQUEST";
export const GET_SINGLE_TO_CREATE_ACCOUNT_HEADER_SUCCESS = "GET_SINGLE_TO_CREATE_ACCOUNT_HEADER_SUCCESS";
export const GET_SINGLE_TO_CREATE_ACCOUNT_HEADER_FAIL = "GET_SINGLE_TO_CREATE_ACCOUNT_HEADER_FAIL";
export const GET_SINGLE_TO_CREATE_ACCOUNT_HEADER_RESET = "GET_SINGLE_TO_CREATE_ACCOUNT_HEADER_RESET";

export const GET_SINGLE_TO_EDIT_ACCOUNT_HEADER_REQUEST = "GET_SINGLE_TO_EDIT_ACCOUNT_HEADER_REQUEST";
export const GET_SINGLE_TO_EDIT_ACCOUNT_HEADER_SUCCESS = "GET_SINGLE_TO_EDIT_ACCOUNT_HEADER_SUCCESS";
export const GET_SINGLE_TO_EDIT_ACCOUNT_HEADER_FAIL = "GET_SINGLE_TO_EDIT_ACCOUNT_HEADER_FAIL";
export const GET_SINGLE_TO_EDIT_ACCOUNT_HEADER_RESET = "GET_SINGLE_TO_EDIT_ACCOUNT_HEADER_RESET";

export const GET_SINGLE_DETAIL_ACCOUNT_HEADER_REQUEST = "GET_SINGLE_DETAIL_ACCOUNT_HEADER_REQUEST";
export const GET_SINGLE_DETAIL_ACCOUNT_HEADER_SUCCESS = "GET_SINGLE_DETAIL_ACCOUNT_HEADER_SUCCESS";
export const GET_SINGLE_DETAIL_ACCOUNT_HEADER_FAIL = "GET_SINGLE_DETAIL_ACCOUNT_HEADER_FAIL";
export const GET_SINGLE_DETAIL_ACCOUNT_HEADER_RESET = "GET_SINGLE_DETAIL_ACCOUNT_HEADER_RESET";

export const POST_ACCOUNT_HEADER_REQUEST = "POST_ACCOUNT_HEADER_REQUEST";
export const POST_ACCOUNT_HEADER_SUCCESS = "POST_ACCOUNT_HEADER_SUCCESS";
export const POST_ACCOUNT_HEADER_FAIL = "POST_ACCOUNT_HEADER_FAIL";
export const POST_ACCOUNT_HEADER_RESET = "POST_ACCOUNT_HEADER_RESET";

export const PUT_ACCOUNT_HEADER_REQUEST = "PUT_ACCOUNT_HEADER_REQUEST";
export const PUT_ACCOUNT_HEADER_SUCCESS = "PUT_ACCOUNT_HEADER_SUCCESS";
export const PUT_ACCOUNT_HEADER_FAIL = "PUT_ACCOUNT_HEADER_FAIL";
export const PUT_ACCOUNT_HEADER_RESET = "PUT_ACCOUNT_HEADER_RESET";