export const GET_ALL_ONE_TIME_BILL_REQUEST = "GET_ALL_ONE_TIME_BILL_REQUEST";
export const GET_ALL_ONE_TIME_BILL_SUCCESS = "GET_ALL_ONE_TIME_BILL_SUCCESS";
export const GET_ALL_ONE_TIME_BILL_FAIL = "GET_ALL_ONE_TIME_BILL_FAIL";
export const GET_ALL_ONE_TIME_BILL_RESET = "GET_ALL_ONE_TIME_BILL_RESET";

export const GET_BULK_EDIT_ONE_TIME_BILL_REQUEST =
  "GET_BULK_EDIT_ONE_TIME_BILL_REQUEST";
export const GET_BULK_EDIT_ONE_TIME_BILL_SUCCESS =
  "GET_BULK_EDIT_ONE_TIME_BILL_SUCCESS";
export const GET_BULK_EDIT_ONE_TIME_BILL_FAIL =
  "GET_BULK_EDIT_ONE_TIME_BILL_FAIL";
export const GET_BULK_EDIT_ONE_TIME_BILL_RESET =
  "GET_BULK_EDIT_ONE_TIME_BILL_RESET";

export const POST_ONE_TIME_BILL_REQUEST = "POST_ONE_TIME_BILL_REQUEST";
export const POST_ONE_TIME_BILL_SUCCESS = "POST_ONE_TIME_BILL_SUCCESS";
export const POST_ONE_TIME_BILL_FAIL = "POST_ONE_TIME_BILL_FAIL";
export const POST_ONE_TIME_BILL_RESET = "POST_ONE_TIME_BILL_RESET";
