export const GET_ALL_ONE_TIME_BILL_PRINT_REQUEST =
  "GET_ALL_ONE_TIME_BILL_PRINT_REQUEST";
export const GET_ALL_ONE_TIME_BILL_PRINT_SUCCESS =
  "GET_ALL_ONE_TIME_BILL_PRINT_SUCCESS";
export const GET_ALL_ONE_TIME_BILL_PRINT_FAIL =
  "GET_ALL_ONE_TIME_BILL_PRINT_FAIL";
export const GET_ALL_ONE_TIME_BILL_PRINT_RESET =
  "GET_ALL_ONE_TIME_BILL_PRINT_RESET";

export const GET_PRINT_ONE_TIME_BILL_PRINT_REQUEST =
  "GET_PRINT_ONE_TIME_BILL_PRINT_REQUEST";
export const GET_PRINT_ONE_TIME_BILL_PRINT_SUCCESS =
  "GET_PRINT_ONE_TIME_BILL_PRINT_SUCCESS";
export const GET_PRINT_ONE_TIME_BILL_PRINT_FAIL =
  "GET_PRINT_ONE_TIME_BILL_PRINT_FAIL";
export const GET_PRINT_ONE_TIME_BILL_PRINT_RESET =
  "GET_PRINT_ONE_TIME_BILL_PRINT_RESET";
