export const GET_ALL_ADMIT_STUDENT_REQUEST = "GET_ALL_ADMIT_STUDENT_REQUEST";
export const GET_ALL_ADMIT_STUDENT_SUCCESS = "GET_ALL_ADMIT_STUDENT_SUCCESS";
export const GET_ALL_ADMIT_STUDENT_FAIL = "GET_ALL_ADMIT_STUDENT_FAIL";
export const GET_ALL_ADMIT_STUDENT_RESET = "GET_ALL_ADMIT_STUDENT_RESET";

export const GET_ACTIVE_STUDENT_FOR_LEDGERONLY_REQUEST =
  "GET_ACTIVE_STUDENT_FOR_LEDGERONLY_REQUEST";
export const GET_ACTIVE_STUDENT_FOR_LEDGERONLY_SUCCESS =
  "GET_ACTIVE_STUDENT_FOR_LEDGERONLY_SUCCESS";
export const GET_ACTIVE_STUDENT_FOR_LEDGERONLY_FAIL =
  "GET_ACTIVE_STUDENT_FOR_LEDGERONLY_FAIL";
export const GET_ACTIVE_STUDENT_FOR_LEDGERONLY_RESET =
  "GET_ACTIVE_STUDENT_FOR_LEDGERONLY_RESET";

export const GET_BULK_EDIT_ADMIT_STUDENT_REQUEST =
  "GET_BULK_EDIT_ADMIT_STUDENT_REQUEST";
export const GET_BULK_EDIT_ADMIT_STUDENT_SUCCESS =
  "GET_BULK_EDIT_ADMIT_STUDENT_SUCCESS";
export const GET_BULK_EDIT_ADMIT_STUDENT_FAIL =
  "GET_BULK_EDIT_ADMIT_STUDENT_FAIL";
export const GET_BULK_EDIT_ADMIT_STUDENT_RESET =
  "GET_BULK_EDIT_ADMIT_STUDENT_RESET";
