export const GET_ALL_FISCAL_YEAR_REQUEST = "GET_ALL_FISCAL_YEAR_REQUEST";
export const GET_ALL_FISCAL_YEAR_SUCCESS = "GET_ALL_FISCAL_YEAR_SUCCESS";
export const GET_ALL_FISCAL_YEAR_FAIL = "GET_ALL_FISCAL_YEAR_FAIL";
export const GET_ALL_FISCAL_YEAR_RESET = "GET_ALL_FISCAL_YEAR_RESET";

export const GET_LIST_FISCAL_YEAR_REQUEST = "GET_LIST_FISCAL_YEAR_REQUEST";
export const GET_LIST_FISCAL_YEAR_SUCCESS = "GET_LIST_FISCAL_YEAR_SUCCESS";
export const GET_LIST_FISCAL_YEAR_FAIL = "GET_LIST_FISCAL_YEAR_FAIL";
export const GET_LIST_FISCAL_YEAR_RESET = "GET_LIST_FISCAL_YEAR_RESET";

export const GET_SINGLE_TO_CREATE_FISCAL_YEAR_REQUEST =
  "GET_SINGLE_TO_CREATE_FISCAL_YEAR_REQUEST";
export const GET_SINGLE_TO_CREATE_FISCAL_YEAR_SUCCESS =
  "GET_SINGLE_TO_CREATE_FISCAL_YEAR_SUCCESS";
export const GET_SINGLE_TO_CREATE_FISCAL_YEAR_FAIL =
  "GET_SINGLE_TO_CREATE_FISCAL_YEAR_FAIL";
export const GET_SINGLE_TO_CREATE_FISCAL_YEAR_RESET =
  "GET_SINGLE_TO_CREATE_FISCAL_YEAR_RESET";

export const GET_SINGLE_TO_EDIT_FISCAL_YEAR_REQUEST =
  "GET_SINGLE_TO_EDIT_FISCAL_YEAR_REQUEST";
export const GET_SINGLE_TO_EDIT_FISCAL_YEAR_SUCCESS =
  "GET_SINGLE_TO_EDIT_FISCAL_YEAR_SUCCESS";
export const GET_SINGLE_TO_EDIT_FISCAL_YEAR_FAIL =
  "GET_SINGLE_TO_EDIT_FISCAL_YEAR_FAIL";
export const GET_SINGLE_TO_EDIT_FISCAL_YEAR_RESET =
  "GET_SINGLE_TO_EDIT_FISCAL_YEAR_RESET";

export const GET_SINGLE_DETAIL_FISCAL_YEAR_REQUEST =
  "GET_SINGLE_DETAIL_FISCAL_YEAR_REQUEST";
export const GET_SINGLE_DETAIL_FISCAL_YEAR_SUCCESS =
  "GET_SINGLE_DETAIL_FISCAL_YEAR_SUCCESS";
export const GET_SINGLE_DETAIL_FISCAL_YEAR_FAIL =
  "GET_SINGLE_DETAIL_FISCAL_YEAR_FAIL";
export const GET_SINGLE_DETAIL_FISCAL_YEAR_RESET =
  "GET_SINGLE_DETAIL_FISCAL_YEAR_RESET";

export const POST_FISCAL_YEAR_REQUEST = "POST_FISCAL_YEAR_REQUEST";
export const POST_FISCAL_YEAR_SUCCESS = "POST_FISCAL_YEAR_SUCCESS";
export const POST_FISCAL_YEAR_FAIL = "POST_FISCAL_YEAR_FAIL";
export const POST_FISCAL_YEAR_RESET = "POST_FISCAL_YEAR_RESET";

export const PUT_FISCAL_YEAR_REQUEST = "PUT_FISCAL_YEAR_REQUEST";
export const PUT_FISCAL_YEAR_SUCCESS = "PUT_FISCAL_YEAR_SUCCESS";
export const PUT_FISCAL_YEAR_FAIL = "PUT_FISCAL_YEAR_FAIL";
export const PUT_FISCAL_YEAR_RESET = "PUT_FISCAL_YEAR_RESET";
