export const GET_ALL_STUDENT_LEDGER_REQUEST = "GET_ALL_STUDENT_LEDGER_REQUEST";
export const GET_ALL_STUDENT_LEDGER_SUCCESS = "GET_ALL_STUDENT_LEDGER_SUCCESS";
export const GET_ALL_STUDENT_LEDGER_FAIL = "GET_ALL_STUDENT_LEDGER_FAIL";
export const GET_ALL_STUDENT_LEDGER_RESET = "GET_ALL_STUDENT_LEDGER_RESET";

export const GET_LIST_STUDENT_LEDGER_REQUEST =
  "GET_LIST_STUDENT_LEDGER_REQUEST";
export const GET_LIST_STUDENT_LEDGER_SUCCESS =
  "GET_LIST_STUDENT_LEDGER_SUCCESS";
export const GET_LIST_STUDENT_LEDGER_FAIL = "GET_LIST_STUDENT_LEDGER_FAIL";
export const GET_LIST_STUDENT_LEDGER_RESET = "GET_LIST_STUDENT_LEDGER_RESET";

export const POST_STUDENT_LEDGER_REQUEST = "POST_STUDENT_LEDGER_REQUEST";
export const POST_STUDENT_LEDGER_SUCCESS = "POST_STUDENT_LEDGER_SUCCESS";
export const POST_STUDENT_LEDGER_FAIL = "POST_STUDENT_LEDGER_FAIL";
export const POST_STUDENT_LEDGER_RESET = "POST_STUDENT_LEDGER_RESET";
