export const GET_ALL_STUDENT_LEDGER_REQUEST = "GET_ALL_STUDENT_LEDGER_REQUEST";
export const GET_ALL_STUDENT_LEDGER_SUCCESS = "GET_ALL_STUDENT_LEDGER_SUCCESS";
export const GET_ALL_STUDENT_LEDGER_FAIL = "GET_ALL_STUDENT_LEDGER_FAIL";
export const GET_ALL_STUDENT_LEDGER_RESET = "GET_ALL_STUDENT_LEDGER_RESET";

export const GET_LIST_STUDENT_LEDGER_REQUEST =
  "GET_LIST_STUDENT_LEDGER_REQUEST";
export const GET_LIST_STUDENT_LEDGER_SUCCESS =
  "GET_LIST_STUDENT_LEDGER_SUCCESS";
export const GET_LIST_STUDENT_LEDGER_FAIL = "GET_LIST_STUDENT_LEDGER_FAIL";
export const GET_LIST_STUDENT_LEDGER_RESET = "GET_LIST_STUDENT_LEDGER_RESET";

export const POST_STUDENT_LEDGER_REQUEST = "POST_STUDENT_LEDGER_REQUEST";
export const POST_STUDENT_LEDGER_SUCCESS = "POST_STUDENT_LEDGER_SUCCESS";
export const POST_STUDENT_LEDGER_FAIL = "POST_STUDENT_LEDGER_FAIL";
export const POST_STUDENT_LEDGER_RESET = "POST_STUDENT_LEDGER_RESET";

export const GET_ACTIVE_STUDENT_ONLY_REQUEST =
  "GET_ACTIVE_STUDENT_ONLY_REQUEST";
export const GET_ACTIVE_STUDENT_ONLY_SUCCESS =
  "GET_ACTIVE_STUDENT_ONLY_SUCCESS";
export const GET_ACTIVE_STUDENT_ONLY_FAIL = "GET_ACTIVE_STUDENT_ONLY_FAIL";
export const GET_ACTIVE_STUDENT_ONLY_RESET = "GET_ACTIVE_STUDENT_ONLY_RESET";

export const GET_UNIVERSITY_FACULTY_REQUEST = "GET_UNIVERSITY_FACULTY_REQUEST";
export const GET_UNIVERSITY_FACULTY_SUCCESS = "GET_UNIVERSITY_FACULTY_SUCCESS";
export const GET_UNIVERSITY_FACULTY_FAIL = "GET_UNIVERSITY_FACULTY_FAIL";
export const GET_UNIVERSITY_FACULTY_RESET = "GET_UNIVERSITY_FACULTY_RESET";
