export const GET_ALL_MONTHLY_FEE_LINK_REQUEST =
  "GET_ALL_MONTHLY_FEE_LINK_REQUEST";
export const GET_ALL_MONTHLY_FEE_LINK_SUCCESS =
  "GET_ALL_MONTHLY_FEE_LINK_SUCCESS";
export const GET_ALL_MONTHLY_FEE_LINK_FAIL = "GET_ALL_MONTHLY_FEE_LINK_FAIL";
export const GET_ALL_MONTHLY_FEE_LINK_RESET = "GET_ALL_MONTHLY_FEE_LINK_RESET";

export const GET_LIST_MONTHLY_FEE_LINK_REQUEST =
  "GET_LIST_MONTHLY_FEE_LINK_REQUEST";
export const GET_LIST_MONTHLY_FEE_LINK_SUCCESS =
  "GET_LIST_MONTHLY_FEE_LINK_SUCCESS";
export const GET_LIST_MONTHLY_FEE_LINK_FAIL = "GET_LIST_MONTHLY_FEE_LINK_FAIL";
export const GET_LIST_MONTHLY_FEE_LINK_RESET =
  "GET_LIST_MONTHLY_FEE_LINK_RESET";

export const GET_SINGLE_TO_CREATE_MONTHLY_FEE_LINK_REQUEST =
  "GET_SINGLE_TO_CREATE_MONTHLY_FEE_LINK_REQUEST";
export const GET_SINGLE_TO_CREATE_MONTHLY_FEE_LINK_SUCCESS =
  "GET_SINGLE_TO_CREATE_MONTHLY_FEE_LINK_SUCCESS";
export const GET_SINGLE_TO_CREATE_MONTHLY_FEE_LINK_FAIL =
  "GET_SINGLE_TO_CREATE_MONTHLY_FEE_LINK_FAIL";
export const GET_SINGLE_TO_CREATE_MONTHLY_FEE_LINK_RESET =
  "GET_SINGLE_TO_CREATE_MONTHLY_FEE_LINK_RESET";

export const GET_SINGLE_TO_EDIT_MONTHLY_FEE_LINK_REQUEST =
  "GET_SINGLE_TO_EDIT_MONTHLY_FEE_LINK_REQUEST";
export const GET_SINGLE_TO_EDIT_MONTHLY_FEE_LINK_SUCCESS =
  "GET_SINGLE_TO_EDIT_MONTHLY_FEE_LINK_SUCCESS";
export const GET_SINGLE_TO_EDIT_MONTHLY_FEE_LINK_FAIL =
  "GET_SINGLE_TO_EDIT_MONTHLY_FEE_LINK_FAIL";
export const GET_SINGLE_TO_EDIT_MONTHLY_FEE_LINK_RESET =
  "GET_SINGLE_TO_EDIT_MONTHLY_FEE_LINK_RESET";

export const POST_MONTHLY_FEE_LINK_REQUEST = "POST_MONTHLY_FEE_LINK_REQUEST";
export const POST_MONTHLY_FEE_LINK_SUCCESS = "POST_MONTHLY_FEE_LINK_SUCCESS";
export const POST_MONTHLY_FEE_LINK_FAIL = "POST_MONTHLY_FEE_LINK_FAIL";
export const POST_MONTHLY_FEE_LINK_RESET = "POST_MONTHLY_FEE_LINK_RESET";

export const PUT_MONTHLY_FEE_LINK_REQUEST = "PUT_MONTHLY_FEE_LINK_REQUEST";
export const PUT_MONTHLY_FEE_LINK_SUCCESS = "PUT_MONTHLY_FEE_LINK_SUCCESS";
export const PUT_MONTHLY_FEE_LINK_FAIL = "PUT_MONTHLY_FEE_LINK_FAIL";
export const PUT_MONTHLY_FEE_LINK_RESET = "PUT_MONTHLY_FEE_LINK_RESET";
