export const GET_ALL_FEE_COLLECTION_REQUEST = "GET_ALL_FEE_COLLECTION_REQUEST";
export const GET_ALL_FEE_COLLECTION_SUCCESS = "GET_ALL_FEE_COLLECTION_SUCCESS";
export const GET_ALL_FEE_COLLECTION_FAIL = "GET_ALL_FEE_COLLECTION_FAIL";
export const GET_ALL_FEE_COLLECTION_RESET = "GET_ALL_FEE_COLLECTION_RESET";

export const GET_LIST_FEE_COLLECTION_REQUEST =
  "GET_LIST_FEE_COLLECTION_REQUEST";
export const GET_LIST_FEE_COLLECTION_SUCCESS =
  "GET_LIST_FEE_COLLECTION_SUCCESS";
export const GET_LIST_FEE_COLLECTION_FAIL = "GET_LIST_FEE_COLLECTION_FAIL";
export const GET_LIST_FEE_COLLECTION_RESET = "GET_LIST_FEE_COLLECTION_RESET";

export const GET_PRINT_FEE_COLLECTION_REQUEST =
  "GET_PRINT_FEE_COLLECTION_REQUEST";
export const GET_PRINT_FEE_COLLECTION_SUCCESS =
  "GET_PRINT_FEE_COLLECTION_SUCCESS";
export const GET_PRINT_FEE_COLLECTION_FAIL = "GET_PRINT_FEE_COLLECTION_FAIL";
export const GET_PRINT_FEE_COLLECTION_RESET = "GET_PRINT_FEE_COLLECTION_RESET";
