export const GET_ALL_STUDENT_DUE_REQUEST = "GET_ALL_STUDENT_DUE_REQUEST";
export const GET_ALL_STUDENT_DUE_SUCCESS = "GET_ALL_STUDENT_DUE_SUCCESS";
export const GET_ALL_STUDENT_DUE_FAIL = "GET_ALL_STUDENT_DUE_FAIL";
export const GET_ALL_STUDENT_DUE_RESET = "GET_ALL_STUDENT_DUE_RESET";

export const GET_LIST_STUDENT_DUE_REQUEST = "GET_LIST_STUDENT_DUE_REQUEST";
export const GET_LIST_STUDENT_DUE_SUCCESS = "GET_LIST_STUDENT_DUE_SUCCESS";
export const GET_LIST_STUDENT_DUE_FAIL = "GET_LIST_STUDENT_DUE_FAIL";
export const GET_LIST_STUDENT_DUE_RESET = "GET_LIST_STUDENT_DUE_RESET";

export const GET_PRINT_STUDENT_DUE_REQUEST = "GET_PRINT_STUDENT_DUE_REQUEST";
export const GET_PRINT_STUDENT_DUE_SUCCESS = "GET_PRINT_STUDENT_DUE_SUCCESS";
export const GET_PRINT_STUDENT_DUE_FAIL = "GET_PRINT_STUDENT_DUE_FAIL";
export const GET_PRINT_STUDENT_DUE_RESET = "GET_PRINT_STUDENT_DUE_RESET";
