export const GET_ALL_ACCOUNT_GROUP_REQUEST = "GET_ALL_ACCOUNT_GROUP_REQUEST";
export const GET_ALL_ACCOUNT_GROUP_SUCCESS = "GET_ALL_ACCOUNT_GROUP_SUCCESS";
export const GET_ALL_ACCOUNT_GROUP_FAIL = "GET_ALL_ACCOUNT_GROUP_FAIL";
export const GET_ALL_ACCOUNT_GROUP_RESET = "GET_ALL_ACCOUNT_GROUP_RESET";

export const GET_LIST_ACCOUNT_GROUP_REQUEST = "GET_LIST_ACCOUNT_GROUP_REQUEST";
export const GET_LIST_ACCOUNT_GROUP_SUCCESS = "GET_LIST_ACCOUNT_GROUP_SUCCESS";
export const GET_LIST_ACCOUNT_GROUP_FAIL = "GET_LIST_ACCOUNT_GROUP_FAIL";
export const GET_LIST_ACCOUNT_GROUP_RESET = "GET_LIST_ACCOUNT_GROUP_RESET";

export const GET_SINGLE_CREATE_ACCOUNT_GROUP_REQUEST = "GET_SINGLE_CREATE_ACCOUNT_GROUP_REQUEST";
export const GET_SINGLE_CREATE_ACCOUNT_GROUP_SUCCESS = "GET_SINGLE_CREATE_ACCOUNT_GROUP_SUCCESS";
export const GET_SINGLE_CREATE_ACCOUNT_GROUP_FAIL = "GET_SINGLE_CREATE_ACCOUNT_GROUP_FAIL";
export const GET_SINGLE_CREATE_ACCOUNT_GROUP_RESET = "GET_SINGLE_CREATE_ACCOUNT_GROUP_RESET";

export const GET_SINGLE_EDIT_ACCOUNT_GROUP_REQUEST = "GET_SINGLE_EDIT_ACCOUNT_GROUP_REQUEST";
export const GET_SINGLE_EDIT_ACCOUNT_GROUP_SUCCESS = "GET_SINGLE_EDIT_ACCOUNT_GROUP_SUCCESS";
export const GET_SINGLE_EDIT_ACCOUNT_GROUP_FAIL = "GET_SINGLE_EDIT_ACCOUNT_GROUP_FAIL";
export const GET_SINGLE_EDIT_ACCOUNT_GROUP_RESET = "GET_SINGLE_EDIT_ACCOUNT_GROUP_RESET";

export const POST_ACCOUNT_GROUP_REQUEST = "POST_ACCOUNT_GROUP_REQUEST";
export const POST_ACCOUNT_GROUP_SUCCESS = "POST_ACCOUNT_GROUP_SUCCESS";
export const POST_ACCOUNT_GROUP_FAIL = "POST_ACCOUNT_GROUP_FAIL";
export const POST_ACCOUNT_GROUP_RESET = "POST_ACCOUNT_GROUP_RESET";

export const PUT_ACCOUNT_GROUP_REQUEST = "PUT_ACCOUNT_GROUP_REQUEST";
export const PUT_ACCOUNT_GROUP_SUCCESS = "PUT_ACCOUNT_GROUP_SUCCESS";
export const PUT_ACCOUNT_GROUP_FAIL = "PUT_ACCOUNT_GROUP_FAIL";
export const PUT_ACCOUNT_GROUP_RESET = "PUT_ACCOUNT_GROUP_RESET";