export const GET_ALL_ACCOUNT_TYPE_REQUEST = "GET_ALL_ACCOUNT_TYPE_REQUEST";
export const GET_ALL_ACCOUNT_TYPE_SUCCESS = "GET_ALL_ACCOUNT_TYPE_SUCCESS";
export const GET_ALL_ACCOUNT_TYPE_FAIL = "GET_ALL_ACCOUNT_TYPE_FAIL";
export const GET_ALL_ACCOUNT_TYPE_RESET = "GET_ALL_ACCOUNT_TYPE_RESET";

export const GET_LIST_ACCOUNT_TYPE_REQUEST = "GET_LIST_ACCOUNT_TYPE_REQUEST";
export const GET_LIST_ACCOUNT_TYPE_SUCCESS = "GET_LIST_ACCOUNT_TYPE_SUCCESS";
export const GET_LIST_ACCOUNT_TYPE_FAIL = "GET_LIST_ACCOUNT_TYPE_FAIL";
export const GET_LIST_ACCOUNT_TYPE_RESET = "GET_LIST_ACCOUNT_TYPE_RESET";

export const GET_SINGLE_TO_CREATE_ACCOUNT_TYPE_REQUEST =
  "GET_SINGLE_TO_CREATE_ACCOUNT_TYPE_REQUEST";
export const GET_SINGLE_TO_CREATE_ACCOUNT_TYPE_SUCCESS =
  "GET_SINGLE_TO_CREATE_ACCOUNT_TYPE_SUCCESS";
export const GET_SINGLE_TO_CREATE_ACCOUNT_TYPE_FAIL =
  "GET_SINGLE_TO_CREATE_ACCOUNT_TYPE_FAIL";
export const GET_SINGLE_TO_CREATE_ACCOUNT_TYPE_RESET =
  "GET_SINGLE_TO_CREATE_ACCOUNT_TYPE_RESET";

export const GET_SINGLE_TO_EDIT_ACCOUNT_TYPE_REQUEST =
  "GET_SINGLE_TO_EDIT_ACCOUNT_TYPE_REQUEST";
export const GET_SINGLE_TO_EDIT_ACCOUNT_TYPE_SUCCESS =
  "GET_SINGLE_TO_EDIT_ACCOUNT_TYPE_SUCCESS";
export const GET_SINGLE_TO_EDIT_ACCOUNT_TYPE_FAIL =
  "GET_SINGLE_TO_EDIT_ACCOUNT_TYPE_FAIL";
export const GET_SINGLE_TO_EDIT_ACCOUNT_TYPE_RESET =
  "GET_SINGLE_TO_EDIT_ACCOUNT_TYPE_RESET";

export const GET_SINGLE_DETAIL_ACCOUNT_TYPE_REQUEST =
  "GET_SINGLE_DETAIL_ACCOUNT_TYPE_REQUEST";
export const GET_SINGLE_DETAIL_ACCOUNT_TYPE_SUCCESS =
  "GET_SINGLE_DETAIL_ACCOUNT_TYPE_SUCCESS";
export const GET_SINGLE_DETAIL_ACCOUNT_TYPE_FAIL =
  "GET_SINGLE_DETAIL_ACCOUNT_TYPE_FAIL";
export const GET_SINGLE_DETAIL_ACCOUNT_TYPE_RESET =
  "GET_SINGLE_DETAIL_ACCOUNT_TYPE_RESET";

export const POST_ACCOUNT_TYPE_REQUEST = "POST_ACCOUNT_TYPE_REQUEST";
export const POST_ACCOUNT_TYPE_SUCCESS = "POST_ACCOUNT_TYPE_SUCCESS";
export const POST_ACCOUNT_TYPE_FAIL = "POST_ACCOUNT_TYPE_FAIL";
export const POST_ACCOUNT_TYPE_RESET = "POST_ACCOUNT_TYPE_RESET";

export const PUT_ACCOUNT_TYPE_REQUEST = "PUT_ACCOUNT_TYPE_REQUEST";
export const PUT_ACCOUNT_TYPE_SUCCESS = "PUT_ACCOUNT_TYPE_SUCCESS";
export const PUT_ACCOUNT_TYPE_FAIL = "PUT_ACCOUNT_TYPE_FAIL";
export const PUT_ACCOUNT_TYPE_RESET = "PUT_ACCOUNT_TYPE_RESET";
