export const GET_ALL_BILL_GENERATE_REQUEST = "GET_ALL_BILL_GENERATE_REQUEST";
export const GET_ALL_BILL_GENERATE_SUCCESS = "GET_ALL_BILL_GENERATE_SUCCESS";
export const GET_ALL_BILL_GENERATE_FAIL = "GET_ALL_BILL_GENERATE_FAIL";
export const GET_ALL_BILL_GENERATE_RESET = "GET_ALL_BILL_GENERATE_RESET";

export const GET_ACTIVE_STUDENT_FOR_BILL_GENERATE_REQUEST =
  "GET_ACTIVE_STUDENT_FOR_BILL_GENERATE_REQUEST";
export const GET_ACTIVE_STUDENT_FOR_BILL_GENERATE_SUCCESS =
  "GET_ACTIVE_STUDENT_FOR_BILL_GENERATE_SUCCESS";
export const GET_ACTIVE_STUDENT_FOR_BILL_GENERATE_FAIL =
  "GET_ACTIVE_STUDENT_FOR_BILL_GENERATE_FAIL";
export const GET_ACTIVE_STUDENT_FOR_BILL_GENERATE_RESET =
  "GET_ACTIVE_STUDENT_FOR_BILL_GENERATE_RESET";

export const GET_BULK_EDIT_BILL_GENERATE_REQUEST =
  "GET_BULK_EDIT_BILL_GENERATE_REQUEST";
export const GET_BULK_EDIT_BILL_GENERATE_SUCCESS =
  "GET_BULK_EDIT_BILL_GENERATE_SUCCESS";
export const GET_BULK_EDIT_BILL_GENERATE_FAIL =
  "GET_BULK_EDIT_BILL_GENERATE_FAIL";
export const GET_BULK_EDIT_BILL_GENERATE_RESET =
  "GET_BULK_EDIT_BILL_GENERATE_RESET";

export const GET_EXTRA_FEE_BILL_GENERATE_REQUEST =
  "GET_EXTRA_FEE_BILL_GENERATE_REQUEST";
export const GET_EXTRA_FEE_BILL_GENERATE_SUCCESS =
  "GET_EXTRA_FEE_BILL_GENERATE_SUCCESS";
export const GET_EXTRA_FEE_BILL_GENERATE_FAIL =
  "GET_EXTRA_FEE_BILL_GENERATE_FAIL";
export const GET_EXTRA_FEE_BILL_GENERATE_RESET =
  "GET_EXTRA_FEE_BILL_GENERATE_RESET";

export const POST_BILL_GENERATE_REQUEST = "POST_BILL_GENERATE_REQUEST";
export const POST_BILL_GENERATE_SUCCESS = "POST_BILL_GENERATE_SUCCESS";
export const POST_BILL_GENERATE_FAIL = "POST_BILL_GENERATE_FAIL";
export const POST_BILL_GENERATE_RESET = "POST_BILL_GENERATE_RESET";
